#!/usr/bin/env python

# Given path to a directory containing VASP input/output files,
# reads the final ground state energy from OSZICAR

import os
import sys
import re

ws_dir = sys.argv[1]
oszicar_path = os.path.join(ws_dir, 'OSZICAR')

# example line of what we're looking at
# 1 F= -.12123579E+02 E0= -.12122671E+02 d E =-.272170E-02

# Now you have two problems
extract_e0_re = re.compile(
	r'^\s*'
	r'(?P<step>\S+)'   # <step num>
	r'\s*F\s*=\s*'     # F =
	r'(?P<F>\S+)'      # <float>
	r'\s*E0\s*=\s*'    # E0 =
	r'(?P<E0>\S+)'     # <float>
	r'\s*d\ ?E\s*=\s*' # d E =
	r'(?P<dE>\S+)'     # <float>
	r'\s*$'
)

e0_list = []
with open(oszicar_path) as f:
	for line in f:
		result = extract_e0_re.match(line)
		if result:
			e0_list.append(result.group('E0'))

if len(e0_list) == 0:
	raise RuntimeError('No E0 line found')

print(e0_list[-1])

